name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-from-tag:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-release.yml
    with:
      tag: ${{ github.ref_name }}
    secrets: inherit
